version: '3.8'

services:
  serve-files:
    image: nginx:alpine
    container_name: serve-files
    volumes:
      - /root/ftp_docs:/usr/share/nginx/html:ro
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
