# docker-compose.yml
version: '3.8'

services:
  # 1) Proxy automático: observa o Docker e faz proxy com base em VIRTUAL_HOST
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.7
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"                 # HTTP-01 challenge e tráfego HTTP
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
