version: '3.8'

networks:
  proxy:
    external: true

services:
  # Grafana
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    # expõe só internamente
    expose:
      - "3000"
    environment:
      - VIRTUAL_HOST=grafana.jotasti.com.br
      - VIRTUAL_PORT=3000
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - proxy

  # Banco MySQL para o Zabbix
  mysql-server:
    image: mysql:8.0.30
    container_name: mysql-server
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=zabbix
    command: >
      --character-set-server=utf8
      --collation-server=utf8_bin
      --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - proxy

  # Zabbix Java Gateway
  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway
    container_name: zabbix-java-gateway
    restart: unless-stopped
    networks:
      - proxy

  # Zabbix Server
  zabbix-server:
    image: zabbix/zabbix-server-mysql
    container_name: zabbix-server
    restart: unless-stopped
    depends_on:
      - mysql-server
      - zabbix-java-gateway
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=zabbix
      - ZBX_JAVAGATEWAY=zabbix-java-gateway
    expose:
      - "10051"
    networks:
      - proxy

  # Zabbix Agent
  zabbix-agent:
    image: zabbix/zabbix-agent
    container_name: zabbix-agent
    restart: unless-stopped
    depends_on:
      - zabbix-server
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=zabbix-server
    expose:
      - "10050"
    networks:
      - proxy

  # Zabbix Web UI
  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql
    container_name: zabbix-web-nginx-mysql
    restart: unless-stopped
    depends_on:
      - mysql-server
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=zabbix
      - VIRTUAL_HOST=zabbix.jotasti.com.br
      - VIRTUAL_PORT=8080
    expose:
      - "8080"
    networks:
      - proxy

volumes:
  grafana_data:
  mysql_data:
