version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: none
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - internal

  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
      # Exemplo de variáveis para nginx-proxy (se usar jwilder/nginx-proxy)
      VIRTUAL_HOST: wiki.jotasti.com.br
      VIRTUAL_PORT: 3000
    restart: unless-stopped
    ports:
      - "85:3000"            # opcional, pode remover se for acessar só via proxy
    networks:
      - internal
      - nginx_proxy

volumes:
  db-data:

networks:
  internal:
    driver: bridge

  nginx_proxy:
    external: true
