version: "3.8"

networks:
  proxy:
    external: true   # sua rede do NPM

services:
  # 1) Banco MariaDB
  phpipam-mariadb:
    image: mariadb:11
    container_name: phpipam-mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=my_root_password
      - MYSQL_DATABASE=phpipam
      - MYSQL_USER=phpipam
      - MYSQL_PASSWORD=my_secret_phpipam_pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - proxy

  # 2) Interface web do phpIPAM
  phpipam-web:
    image: phpipam/phpipam-www:latest
    container_name: phpipam-web
    depends_on:
      - phpipam-mariadb
    restart: unless-stopped
    expose:
      - "80"    # apenas expõe internamente para o proxy
    environment:
      - TZ=America/Sao_Paulo
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_NAME=phpipam
      - IPAM_DATABASE_USER=phpipam
      - IPAM_DATABASE_PASS=my_secret_phpipam_pass
      # após concluir a instalação, descomente a linha abaixo:
       - IPAM_DISABLE_INSTALLER=1
      - VIRTUAL_HOST=phpipam.jotasti.com.br
      - VIRTUAL_PORT=80
      - VIRTUAL_NETWORK=proxy    # para o NPM saber em qual rede procurar
    volumes:
      - phpipam-ca:/usr/local/share/ca-certificates:ro
    networks:
      - proxy

volumes:
  db_data:
  phpipam-ca:
