version: '3.8'

networks:
  proxy:
    external: true

services:
  # 1) Banco de dados do phpIPAM
  phpipam-db:
    image: mariadb:latest
    container_name: phpipam-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=my_secret_mysql_root_pass
      - MYSQL_DATABASE=phpipam
      - MYSQL_USER=phpipam
      - MYSQL_PASSWORD=my_secret_phpipam_pass
    volumes:
      - phpipam-db-data:/var/lib/mysql
    networks:
      - proxy

  # 2) Web do phpIPAM
  phpipam-web:
    image: phpipam/phpipam-www:latest
    container_name: phpipam-web
    restart: unless-stopped
    depends_on:
      - phpipam-db
    environment:
      - TZ=Europe/London
      - IPAM_DATABASE_HOST=phpipam-db
      - IPAM_DATABASE_NAME=phpipam
      - IPAM_DATABASE_USER=phpipam
      - IPAM_DATABASE_PASS=my_secret_phpipam_pass
      - IPAM_DATABASE_WEBHOST=% 
      # para o jwilder/nginx-proxy
      - VIRTUAL_HOST=ipam.jotasti.com.br
      - VIRTUAL_PORT=80
    # expõe só internamente
    expose:
      - "80"
    volumes:
      - phpipam-logo:/phpipam/css/images/logo
      - phpipam-ca:/usr/local/share/ca-certificates:ro
    networks:
      - proxy

  # 3) Cron do phpIPAM
  phpipam-cron:
    image: phpipam/phpipam-cron:latest
    container_name: phpipam-cron
    restart: unless-stopped
    depends_on:
      - phpipam-db
    environment:
      - TZ=Europe/London
      - IPAM_DATABASE_HOST=phpipam-db
      - IPAM_DATABASE_NAME=phpipam
      - IPAM_DATABASE_USER=phpipam
      - IPAM_DATABASE_PASS=my_secret_phpipam_pass
      - SCAN_INTERVAL=1h
    volumes:
      - phpipam-ca:/usr/local/share/ca-certificates:ro
    networks:
      - proxy

volumes:
  phpipam-db-data:
  phpipam-logo:
  phpipam-ca:
