# docker-compose-phpipam.yml
version: '3'

services:
  phpipam-web:
    image: phpipam/phpipam-www:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/London
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=my_secret_phpipam_pass
      - IPAM_DATABASE_WEBHOST=%
    volumes:
      - phpipam-logo:/phpipam/css/images/logo
      - phpipam-ca:/usr/local/share/ca-certificates:ro
    depends_on:
      - phpipam-mariadb
    networks:
      - nginx_proxy

  phpipam-cron:
    image: phpipam/phpipam-cron:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/London
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=my_secret_phpipam_pass
      - SCAN_INTERVAL=1h
    volumes:
      - phpipam-ca:/usr/local/share/ca-certificates:ro
    depends_on:
      - phpipam-mariadb
    networks:
      - nginx_proxy

  phpipam-mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=my_secret_mysql_root_pass
    volumes:
      - phpipam-db-data:/var/lib/mysql
    networks:
      - nginx_proxy

volumes:
  phpipam-db-data:
  phpipam-logo:
  phpipam-ca:

networks:
  nginx_proxy:
    external: true
