version: '3.8'

services:
  db:
    image: mariadb:11.3
    container_name: nextcloud-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=MinhaSenhaRootAqui
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextclouduser
      - MYSQL_PASSWORD=SenhaDoBancoAqui
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - nextcloudnet

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    networks:
      - nextcloudnet

  nextcloud:
    image: nextcloud:31.0.5-apache
    container_name: nextcloud-app
    restart: unless-stopped
    depends_on:
      - db
      - redis
    # REMOVA esse ports se for usar o proxy para HTTPS/HTTP
    # ports:
    #   - "8080:80"
    # em vez disso:
    expose:
      - "80"
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextclouduser
      - MYSQL_PASSWORD=SenhaDoBancoAqui
      - REDIS_HOST=redis
      # estas variáveis são lidas pelo jwilder/nginx-proxy
      - VIRTUAL_HOST=cloud.seudominio.com.br
      - VIRTUAL_PORT=80
    volumes:
      - nextcloud_data:/var/www/html
    networks:
      - nextcloudnet
      - proxy

volumes:
  db_data:
  nextcloud_data:

networks:
  # rede interna exclusiva do Nextcloud
  nextcloudnet:
    driver: bridge
  # rede externa do seu proxy (já existente)
  proxy:
    external: true
